### PR TITLE
2.0: Support Vue.js v3.x

### LINKED ISSUE #73: Support for Vue 3
Since Vue 3 is now in RC, would it be possible to support Vue 3?

### PR DESCRIPTION
**Pull request by namoscato**
Resolves #73.

- [x] Update documentation (i.e. README)
- [x] Update TypeScript definitions
- [x] Cleanup CI

### CODE REVIEW

**Comment by fmeyertoens** [comment]
How do we plan to release this? Can we support both Vue 2 and 3 or do we have to drop support for v2 with this?

**Comment by namoscato** [comment]
@fmeyertoens, I was thinking v2 of this library would drop Vue.js v2 support for simplicity, but it's a good thought. Let me know what you think!

**Comment by fmeyertoens** [comment]
From what I see most libraries make a cut and switch to Vue3 and the breaking changes make it hard to maintain a single code base for both versions. I'd suggest that right before we merge `next` into `master` we make a `v2` branch from `master` where we can implement bugfixes for v2 and `master` will only be compatible with Vue 3.

**Comment by namoscato** [comment]
Yeah, that sounds great to me!

I'll try to wrap up the documentation updates this weekend.

**Comment by namoscato** [comment]
@fmeyertoens, I think this is basically ready now, but if you have time, would you mind glancing over the changes?

I created a `releases/v1` branch which captures the current state of `master`.

_Sidenote: I've been a bit swamped, hence the unresponsiveness on – mostly everything, but thank you for continuing to merge dependency PRs!_

**Pull request merged**
