### PR TITLE
Example added

### PR DESCRIPTION
**Pull request by pavelkrejsa**
Added example how to use $gapi in router's navigation guards.

### CODE REVIEW

**Review by namoscato — APPROVED** [review]
@pavelkrejsa, this is great – thank you!

28916db28b737572a86fc35de4a6254d8ebff812 makes a few minor edits:

1. Update VuePress configuration so this new example shows up in the sidebar.
2. Rename the example from "Navigation Guard" to "Vue Router". I'm open to feedback on this, but my guess is people might not know what "Navigation Guard" means, given it's a Vue Router-specific topic.
3. Minor wording and formatting edits.

Let me know if you're cool with these changes, and we can get this merged!

**Comment by pavelkrejsa** [comment]
Dear Nick,
I am just fine with all proposed changes. Is there a formal Git process I
need to follow to approve yours proposals?
I can create a new pull request with that Plugin style configuration of
vue-gapi, if you are interested?

Best regards
Pavel K.

**Comment by namoscato** [comment]
> Is there a formal Git process I need to follow to approve yours proposals? I can create a new pull request with that Plugin style configuration of vue-gapi, if you are interested?

Nope, this pull request is fine! I'll merge it now.

**Comment by namoscato** [comment]
It's live [over here](https://vue-gapi.github.io/vue-gapi/examples/vue-router.html).

Thanks again for the contribution!

**Comment by pavelkrejsa** [comment]
Great,
thank you and all others for this plugin, it helped me a lot with my
project. I will try to contribute more in the future.
Pavel K.

**Pull request merged**
